/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author G-up
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     * @param pq
     */
    public frmMain(String pq) {
        initComponents();
        if("1".equals(pq))
            btnNhanVien.setEnabled(false);
        
        if("1".equals(pq))
            lbhello.setText("Hello Nhân Viên");
        else{
            lbhello.setText("Hello Quản Lý");
        }
        
        
    }

    private frmMain() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbhello = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        spMain = new javax.swing.JSplitPane();
        jptraii = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JButton();
        kButton11 = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnNhapHang = new javax.swing.JButton();
        btnPhieuNhap = new javax.swing.JButton();
        btnNhaCungCap = new javax.swing.JButton();
        jpphai = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbhello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/admin.png"))); // NOI18N
        jPanel1.add(lbhello, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 130, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 34)); // NOI18N
        jLabel2.setText("Quản     Lý     Bán     Sữa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 400, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/milk (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 40, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/milk.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/milk-box (2).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -8, -1, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/milk (2).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 50));

        spMain.setMinimumSize(new java.awt.Dimension(120, 462));

        jptraii.setBackground(new java.awt.Color(0, 255, 255));
        jptraii.setMinimumSize(new java.awt.Dimension(140, 460));
        jptraii.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 102, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/home.png"))); // NOI18N
        jLabel3.setIconTextGap(20);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jptraii.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 40, 40));

        btnBanHang.setBackground(java.awt.Color.cyan);
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/shop.png"))); // NOI18N
        btnBanHang.setText("Bán Hàng");
        btnBanHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnBanHang.setBorderPainted(false);
        btnBanHang.setIconTextGap(10);
        btnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanHangMouseClicked(evt);
            }
        });
        jptraii.add(btnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 140, 40));

        kButton11.setBackground(java.awt.Color.cyan);
        kButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/milk-box (1).png"))); // NOI18N
        kButton11.setText("Sữa");
        kButton11.setAlignmentY(0.0F);
        kButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        kButton11.setBorderPainted(false);
        kButton11.setIconTextGap(10);
        kButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton11MouseClicked(evt);
            }
        });
        jptraii.add(kButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 40));

        btnNhanVien.setBackground(java.awt.Color.cyan);
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/group.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.setIconTextGap(7);
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseClicked(evt);
            }
        });
        jptraii.add(btnNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        btnKhachHang.setBackground(java.awt.Color.cyan);
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/rating.png"))); // NOI18N
        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnKhachHang.setBorderPainted(false);
        btnKhachHang.setIconTextGap(7);
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseClicked(evt);
            }
        });
        jptraii.add(btnKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, 40));

        btnHoaDon.setBackground(java.awt.Color.cyan);
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/bill.png"))); // NOI18N
        btnHoaDon.setText("Hóa Đơn");
        btnHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnHoaDon.setBorderPainted(false);
        btnHoaDon.setIconTextGap(15);
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseClicked(evt);
            }
        });
        jptraii.add(btnHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, 40));

        btnNhapHang.setBackground(java.awt.Color.cyan);
        btnNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/packages.png"))); // NOI18N
        btnNhapHang.setText("Nhập Hàng");
        btnNhapHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnNhapHang.setBorderPainted(false);
        btnNhapHang.setIconTextGap(10);
        btnNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapHangMouseClicked(evt);
            }
        });
        jptraii.add(btnNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 140, 40));

        btnPhieuNhap.setBackground(java.awt.Color.cyan);
        btnPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/checkbox.png"))); // NOI18N
        btnPhieuNhap.setText("Phiếu Nhập");
        btnPhieuNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnPhieuNhap.setBorderPainted(false);
        btnPhieuNhap.setIconTextGap(7);
        btnPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPhieuNhapMouseClicked(evt);
            }
        });
        jptraii.add(btnPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 140, 40));

        btnNhaCungCap.setBackground(java.awt.Color.cyan);
        btnNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/inventory.png"))); // NOI18N
        btnNhaCungCap.setText("Nhà Cung Cấp");
        btnNhaCungCap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnNhaCungCap.setBorderPainted(false);
        btnNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhaCungCapMouseClicked(evt);
            }
        });
        jptraii.add(btnNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 140, 40));

        spMain.setLeftComponent(jptraii);

        jpphai.setkEndColor(new java.awt.Color(102, 102, 255));
        jpphai.setkGradientFocus(1000);
        jpphai.setkStartColor(new java.awt.Color(102, 255, 255));
        jpphai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhSua/dairy-store-milk-shop-signboard-awning-dairy-store-milk-shop-signboard-awning-store-facade-storefront-farmer-159806641.jpg"))); // NOI18N
        jpphai.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 800, 700));
        jpphai.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -2, 1300, -1));

        spMain.setRightComponent(jpphai);

        getContentPane().add(spMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 55, 1290, 700));

        setSize(new java.awt.Dimension(1304, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jpnAnhmain frm = null;
        kButton11.setBackground(Color.CYAN);
        btnPhieuNhap.setBackground(Color.CYAN);
        btnHoaDon.setBackground(Color.CYAN);
        btnNhanVien.setBackground(Color.CYAN);
        btnKhachHang.setBackground(Color.CYAN);
        btnNhaCungCap.setBackground(Color.CYAN);
        frm = new jpnAnhmain();//tao 1 cai moi
        spMain.setRightComponent(frm);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void kButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton11MouseClicked
        jpnSua frm = null;
        kButton11.setBackground(Color.LIGHT_GRAY);
        btnPhieuNhap.setBackground(Color.CYAN);
        btnHoaDon.setBackground(Color.CYAN);
         btnNhanVien.setBackground(Color.CYAN);
         btnKhachHang.setBackground(Color.CYAN);
         btnNhaCungCap.setBackground(Color.CYAN);
        try {
            frm=new jpnSua();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        spMain.setRightComponent(frm);
    }//GEN-LAST:event_kButton11MouseClicked

    private void btnPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhieuNhapMouseClicked
        jpnPhieuNhap pn = null;
        btnPhieuNhap.setBackground(Color.LIGHT_GRAY);
        kButton11.setBackground(Color.CYAN);
        btnHoaDon.setBackground(Color.CYAN);
         btnNhanVien.setBackground(Color.CYAN);
         btnKhachHang.setBackground(Color.CYAN);
         btnNhaCungCap.setBackground(Color.CYAN);
        try {
            pn= new jpnPhieuNhap();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        spMain.setRightComponent(pn);
    }//GEN-LAST:event_btnPhieuNhapMouseClicked

    private void btnHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseClicked
        btnHoaDon.setBackground(Color.LIGHT_GRAY);
        kButton11.setBackground(Color.CYAN);
        btnNhanVien.setBackground(Color.CYAN);
        btnPhieuNhap.setBackground(Color.CYAN);
        btnKhachHang.setBackground(Color.CYAN);
        btnNhaCungCap.setBackground(Color.CYAN);
        jpnHoaDon hd = null;
        try {
            hd = new jpnHoaDon();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        spMain.setRightComponent(hd);
    }//GEN-LAST:event_btnHoaDonMouseClicked

    private void btnNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseClicked
        btnNhanVien.setBackground(Color.LIGHT_GRAY);
        btnHoaDon.setBackground(Color.CYAN);
        kButton11.setBackground(Color.CYAN);
        btnPhieuNhap.setBackground(Color.CYAN);
        btnKhachHang.setBackground(Color.CYAN);
        btnNhaCungCap.setBackground(Color.CYAN);
        jpnNhanVien frm = null;
        try {
            frm = new jpnNhanVien();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
          spMain.setRightComponent(frm);
    }//GEN-LAST:event_btnNhanVienMouseClicked

    private void btnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseClicked
        kButton11.setBackground(Color.CYAN);
        btnPhieuNhap.setBackground(Color.CYAN);
        btnHoaDon.setBackground(Color.CYAN);
        btnNhanVien.setBackground(Color.CYAN);
        btnKhachHang.setBackground(Color.LIGHT_GRAY);
        btnNhaCungCap.setBackground(Color.CYAN);
        jpnKhachHang frm = null;
        try {
            frm = new jpnKhachHang();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        spMain.setRightComponent(frm);
        
    }//GEN-LAST:event_btnKhachHangMouseClicked

    private void btnNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhaCungCapMouseClicked
        kButton11.setBackground(Color.CYAN);
        btnPhieuNhap.setBackground(Color.CYAN);
        btnHoaDon.setBackground(Color.CYAN);
        btnNhanVien.setBackground(Color.CYAN);
        btnKhachHang.setBackground(Color.CYAN);
        btnNhaCungCap.setBackground(Color.LIGHT_GRAY);
        
        jpnNhaCungCap frm = null;
        try {
            frm = new jpnNhaCungCap();//tao 1 cai moi
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        spMain.setRightComponent(frm);
    }//GEN-LAST:event_btnNhaCungCapMouseClicked
    
    String MaNV;
    
    public void SetMaNV(String _MaVN){
        MaNV = _MaVN;
    }
        
    private void btnNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapHangMouseClicked
        
        jpnNhapHang nh = null;
        try {
            nh = new jpnNhapHang(MaNV);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        spMain.setRightComponent(nh);
    }//GEN-LAST:event_btnNhapHangMouseClicked

    private void btnBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseClicked
        jpnBanHang bh = null;
        try {
            bh = new jpnBanHang(MaNV);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        spMain.setRightComponent(bh);
    }//GEN-LAST:event_btnBanHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhaCungCap;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnPhieuNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.k33ptoo.components.KGradientPanel jpphai;
    private javax.swing.JPanel jptraii;
    private javax.swing.JButton kButton11;
    private javax.swing.JLabel lbhello;
    private javax.swing.JSplitPane spMain;
    // End of variables declaration//GEN-END:variables
}
