/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

/**
 *
 * @author G-up
 */
public class jpnAnhmain extends javax.swing.JPanel {

    /**
     * Creates new form jpnAnhmain
     */
    public jpnAnhmain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpphai = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jpphai.setkEndColor(new java.awt.Color(102, 102, 255));
        jpphai.setkGradientFocus(1000);
        jpphai.setkStartColor(new java.awt.Color(102, 255, 255));
        jpphai.setMinimumSize(new java.awt.Dimension(1170, 700));
        jpphai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhSua/dairy-store-milk-shop-signboard-awning-dairy-store-milk-shop-signboard-awning-store-facade-storefront-farmer-159806641.jpg"))); // NOI18N
        jpphai.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 660));
        jpphai.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -2, 1300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1183, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpphai, javax.swing.GroupLayout.DEFAULT_SIZE, 1183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpphai, javax.swing.GroupLayout.PREFERRED_SIZE, 653, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private com.k33ptoo.components.KGradientPanel jpphai;
    // End of variables declaration//GEN-END:variables
}
