/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import Entity.HoaDon;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/**
 *
 * @author G-up
 */
public class jpnHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form jpnHoaDon
     */
    public jpnHoaDon() throws ClassNotFoundException, SQLException {
        initComponents();
        LoadDataTable_HoaDon();
        Date date = new Date();
        dpk_NgayLap.setDate(date);
    }
    
    private void LoadDataControl() throws SQLException, ClassNotFoundException
    {
        if (tbl_HoaDon.getSelectedRow() != -1) {
            //-- Xác định hàng đã click
            int i = tbl_HoaDon.getSelectedRow();
            
            //-- Lấy được danh sách sinh viên
            List<HoaDon> lstHoaDon = DAO.DAOHoaDon.getAllHD();
            //-- Xác định là sản phẩm  nào đang được click
            
            HoaDon sp1 = lstHoaDon.get(i);
            //--- Set giá trị cho các control
            txt_MaHD.setText(sp1.getMaHD());
            txt_MaKH.setText(sp1.getMaKH());
            txt_MaNV.setText(sp1.getMaNV());
            txt_TongTien.setText(String.valueOf(sp1.getTongTien()));
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            try {
                dpk_NgayLap.setDate(dateFormat.parse( sp1.getNgayLap()));
                
                //- Set giá trị của components JXdatepicker
            } catch (ParseException ex) {
                Logger.getLogger(jpnHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }
   

    private void LoadDataTable_HoaDon() throws ClassNotFoundException, SQLException
    {
        List<HoaDon> lstHoaDon = DAO.DAOHoaDon.getAllHD();
        // Thêm các tiêu đề cho bảng hiẻn thị
        DefaultTableModel tblModel = new DefaultTableModel();
        tblModel.addColumn("Mã hoá đơn");
        tblModel.addColumn("Mã khách hàng ");
        tblModel.addColumn("Mã nhân viên");
        tblModel.addColumn("Ngày lập");
        tblModel.addColumn("Tổng tiền");
        
        // Add lần lượt các hàng
        for(HoaDon _hoadon : lstHoaDon)
        {
            Vector<String> row = new Vector<String>();
            row.addElement(String.valueOf(_hoadon.getMaHD()));
            row.addElement(String.valueOf(_hoadon.getMaKH()));
            row.addElement(String.valueOf(_hoadon.getMaNV())); 
            row.addElement(String.valueOf(_hoadon.getNgayLap()));
            row.addElement(String.valueOf(_hoadon.getTongTien()));
            tblModel.addRow(row);
        }
        tbl_HoaDon.setModel(tblModel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JTextField();
        txt_MaKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dpk_NgayLap = new org.jdesktop.swingx.JXDatePicker();
        btn_Xoa = new javax.swing.JButton();
        btn_CTHD = new javax.swing.JButton();
        btn_XuatFile = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDon = new org.jdesktop.swingx.JXTable();

        setMinimumSize(new java.awt.Dimension(1170, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã hoá đơn:");

        txt_MaHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_MaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã khách hàng:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Mã nhân viên:");

        txt_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_MaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaNVActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày lập:");

        txt_TongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tổng tiền:");

        dpk_NgayLap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dpk_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dpk_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        btn_Xoa.setText("Xoá");
        btn_Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaMouseClicked(evt);
            }
        });

        btn_CTHD.setText("CTHD");
        btn_CTHD.setEnabled(false);
        btn_CTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CTHDMouseClicked(evt);
            }
        });

        btn_XuatFile.setText("Xuất File");
        btn_XuatFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XuatFileMouseClicked(evt);
            }
        });

        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LamMoiMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel1.setText("HÓA ĐƠN");

        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_HoaDon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_CTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_XuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_XuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaNVActionPerformed

    private void btn_XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaMouseClicked
        try {
            // TODO add your handling code here:
            DAO.DAOHoaDon.DeleteHD(txt_MaHD.getText());
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        } catch (SQLException ex) {
            Logger.getLogger(jpnHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_XoaMouseClicked

    private void btn_CTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CTHDMouseClicked

        try {
            frmCTHD  frm = new frmCTHD(txt_MaHD.getText());
            frm.pack();
            frm.setVisible(true);
            //frm.dispose();            loi phan nay
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(jpnHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_CTHDMouseClicked

    private void btn_XuatFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XuatFileMouseClicked
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();//goiworkbook
            XSSFSheet spreadsheet = workbook.createSheet("Hoá Đơn");//tao 1 sheet danh sach mang ten hoa don
            XSSFRow row = null;//hang
            Cell cell = null;//cot
            
            row = spreadsheet.createRow((short) 2);//xuong 2 hang
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("DANH SÁCH HOÁ ĐON");
            
            row = spreadsheet.createRow((short) 3);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");//cot 0
            
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã hoá đơn");//cot 1
            
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Mã khách hàng");
            
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Mã nhân viên");
            
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Ngày lập");
            
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Tổng tiền");
            
            //dua du lieu vao 
            List<HoaDon> listItem = DAO.DAOHoaDon.getAllHD();
            for (int i = 0; i < listItem.size(); i++) {
                HoaDon _hoadon = listItem.get(i);
                row = spreadsheet.createRow((short) 4 + i);//dua du lieu list vao hang tiep theo cua so 4 
                row.setHeight((short) 400);
                row.createCell(0).setCellValue(i + 1);//so thu tu vao cot 0 
                row.createCell(1).setCellValue(_hoadon.getMaHD());
                row.createCell(2).setCellValue(_hoadon.getMaKH());
                row.createCell(3).setCellValue(_hoadon.getMaNV());
                row.createCell(4).setCellValue(_hoadon.getNgayLap());
                row.createCell(5).setCellValue(_hoadon.getTongTien());
                //dien du lieu vao
            } 
            //luufile
            FileOutputStream out = new FileOutputStream(new File("C:\\java_luu\\Dshd.xlsx"));
            workbook.write(out);
            out.close();
            JOptionPane.showMessageDialog(this, "Xuất file thành công");
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_btn_XuatFileMouseClicked

    private void btn_LamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LamMoiMouseClicked

        Date a = new Date();

        txt_MaHD.setText("");
        txt_MaKH.setText("");
        txt_MaNV.setText("");
        txt_TongTien.setText("");
        dpk_NgayLap.setDate(a);

        try {
            btn_CTHD.setEnabled(false);
            LoadDataTable_HoaDon();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(jpnHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_LamMoiMouseClicked

    private void tbl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDonMouseClicked
        try {
            LoadDataControl();
        } catch (SQLException ex) {
            Logger.getLogger(jpnHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        btn_CTHD.setEnabled(true);
    }//GEN-LAST:event_tbl_HoaDonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CTHD;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XuatFile;
    private org.jdesktop.swingx.JXDatePicker dpk_NgayLap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable tbl_HoaDon;
    private javax.swing.JTextField txt_MaHD;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
