/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import Entity.NhanVien;
import Entity.Sua;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class jpnNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form jpnNhanVien
     *
     * @throws java.sql.SQLException
     */
    public jpnNhanVien() throws SQLException, ClassNotFoundException {
        initComponents();
        LoadData2table();
    }

    private void LoadData2table() throws SQLException, ClassNotFoundException {
        List<NhanVien> lsNhanViens = DAO.DAONhanVien.getALLnhanvien();
        // Thêm các tiêu đề cho bảng hiẻn thị
        DefaultTableModel tblModel = new DefaultTableModel();
        tblModel.addColumn("Mã nhan vien");
        tblModel.addColumn("Tên nhan vien");
        tblModel.addColumn("Ngay sinh");
        tblModel.addColumn("Địa chỉ");
        tblModel.addColumn("SDT");
        tblModel.addColumn("Phan quyen");
        // Add lần lượt các hàng
        for (NhanVien _nhanVien : lsNhanViens) {
            Vector<String> row = new Vector<String>();
            row.addElement(String.valueOf(_nhanVien.getMaNV()));
            row.addElement(String.valueOf(_nhanVien.getTenNV()));
            row.addElement(String.valueOf(_nhanVien.getNgaySinh()));
            row.addElement(String.valueOf(_nhanVien.getDiaChi()));
            row.addElement(String.valueOf(_nhanVien.getSDT()));
            row.addElement(String.valueOf(_nhanVien.getPhanQuyen()));
            tblModel.addRow(row);
        }
        tbNhanvien.setModel(tblModel);
    }

    private void LoadDataControl() throws SQLException, ClassNotFoundException {
        if (tbNhanvien.getSelectedRow() != -1) {
            //-- Xác định hàng đã click
            int i = tbNhanvien.getSelectedRow();

            //-- Lấy được danh sách sinh viên
            List<NhanVien> lstSanPham = DAO.DAONhanVien.getALLnhanvien();
            //-- Xác định là sản phẩm  nào đang được click

            NhanVien sp1 = lstSanPham.get(i);
            //--- Set giá trị cho các control
            txtManv.setText(sp1.getMaNV());
            txtnv.setText(sp1.getTenNV());
            txtsdt.setText(sp1.getSDT());
            txtdiachi.setText(sp1.getDiaChi());
            txtdate.setToolTipText(sp1.getNgaySinh());
            txtphanquyen.setText(sp1.getPhanQuyen());
            //- Set giá trị của components JXdatepicker
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            try {
                txtdate.setDate(dateFormat.parse(sp1.getNgaySinh()));
            } catch (ParseException ex) {
                Logger.getLogger(jpnNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanvien = new org.jdesktop.swingx.JXTable();
        btThem = new com.k33ptoo.components.KButton();
        btXoa = new com.k33ptoo.components.KButton();
        btsua = new com.k33ptoo.components.KButton();
        btLammoi = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtdate = new org.jdesktop.swingx.JXDatePicker();
        lbphanquyen = new javax.swing.JLabel();
        txtphanquyen = new javax.swing.JTextField();
        lbMANV = new javax.swing.JLabel();
        lbTEN = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        lbDIACHI = new javax.swing.JLabel();
        lbNGAYSINH = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        txtnv = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(1170, 700));
        setName(""); // NOI18N

        tbNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tbNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhanvien);

        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/add.png"))); // NOI18N
        btThem.setText("Thêm");
        btThem.setIconTextGap(50);
        btThem.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btThem.setkEndColor(new java.awt.Color(153, 153, 255));
        btThem.setkForeGround(new java.awt.Color(0, 0, 0));
        btThem.setkHoverColor(new java.awt.Color(0, 102, 204));
        btThem.setkHoverEndColor(new java.awt.Color(0, 153, 204));
        btThem.setkHoverForeGround(new java.awt.Color(0, 102, 204));
        btThem.setkHoverStartColor(new java.awt.Color(0, 51, 153));
        btThem.setkIndicatorColor(new java.awt.Color(0, 0, 0));
        btThem.setkStartColor(new java.awt.Color(0, 204, 204));
        btThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btThemMouseClicked(evt);
            }
        });

        btXoa.setText("Xóa");
        btXoa.setkEndColor(new java.awt.Color(153, 153, 255));
        btXoa.setkForeGround(new java.awt.Color(0, 0, 0));
        btXoa.setkHoverColor(new java.awt.Color(0, 102, 204));
        btXoa.setkHoverEndColor(new java.awt.Color(0, 153, 204));
        btXoa.setkHoverForeGround(new java.awt.Color(0, 102, 204));
        btXoa.setkHoverStartColor(new java.awt.Color(0, 51, 153));
        btXoa.setkIndicatorColor(new java.awt.Color(0, 0, 0));
        btXoa.setkStartColor(new java.awt.Color(0, 204, 204));
        btXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btXoaMouseClicked(evt);
            }
        });

        btsua.setText("Sửa");
        btsua.setkEndColor(new java.awt.Color(153, 153, 255));
        btsua.setkForeGround(new java.awt.Color(0, 0, 0));
        btsua.setkHoverColor(new java.awt.Color(0, 102, 204));
        btsua.setkHoverEndColor(new java.awt.Color(0, 153, 204));
        btsua.setkHoverForeGround(new java.awt.Color(0, 102, 204));
        btsua.setkHoverStartColor(new java.awt.Color(0, 51, 153));
        btsua.setkIndicatorColor(new java.awt.Color(0, 0, 0));
        btsua.setkStartColor(new java.awt.Color(0, 204, 204));
        btsua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsuaMouseClicked(evt);
            }
        });

        btLammoi.setText("Làm mới");
        btLammoi.setkEndColor(new java.awt.Color(153, 153, 255));
        btLammoi.setkForeGround(new java.awt.Color(0, 0, 0));
        btLammoi.setkHoverColor(new java.awt.Color(0, 102, 204));
        btLammoi.setkHoverEndColor(new java.awt.Color(0, 153, 204));
        btLammoi.setkHoverForeGround(new java.awt.Color(0, 102, 204));
        btLammoi.setkHoverStartColor(new java.awt.Color(0, 51, 153));
        btLammoi.setkIndicatorColor(new java.awt.Color(0, 0, 0));
        btLammoi.setkStartColor(new java.awt.Color(0, 204, 204));
        btLammoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLammoiMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("Thông tin nhân viên");

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbphanquyen.setText("Phân quyền");

        lbMANV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbMANV.setText("Mã Nv");

        lbTEN.setText("Tên Nv");

        lbSDT.setText("SDT");

        lbDIACHI.setText("Địa chỉ");

        lbNGAYSINH.setText("Ngày sinh");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSDT)
                            .addComponent(lbDIACHI)
                            .addComponent(lbNGAYSINH)
                            .addComponent(lbTEN)
                            .addComponent(lbMANV))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbphanquyen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMANV))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTEN))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSDT)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDIACHI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNGAYSINH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbphanquyen))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btsua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btsua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanvienMouseClicked
        try {
            // TODO add your handling code here:
            LoadDataControl();
        } catch (SQLException ex) {
            Logger.getLogger(jpnNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbNhanvienMouseClicked

    private void btThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThemMouseClicked
        // TODO add your handling code here:
        //SimpleDateFormat datefr =new SimpleDateFormat("yyy-MM-dd");
        NhanVien _sp = new NhanVien();
        _sp.setMaNV(txtManv.getText());
        _sp.setTenNV(txtnv.getText());
        _sp.setSDT(txtsdt.getText());
        _sp.setDiaChi(txtdiachi.getText());
        _sp.setPhanQuyen(txtphanquyen.getText());

        Date dtn = txtdate.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        _sp.setNgaySinh(dateFormat.format(dtn));

        try {
            DAO.DAONhanVien.InsertSP(_sp);
            JOptionPane.showMessageDialog(this, "Them thành công!");
            LoadData2table();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(jpnNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btThemMouseClicked

    private void btXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXoaMouseClicked
        // TODO add your handling code here:
        try {
            DAO.DAONhanVien.DeleteSP(txtManv.getText());
            LoadData2table();
            btnLammoiMouseClicked(evt);
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
        } catch (SQLException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btXoaMouseClicked

    private void btsuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsuaMouseClicked
        // TODO add your handling code here:
        NhanVien _sp = new NhanVien();
        _sp.setMaNV(txtManv.getText());
        _sp.setTenNV(txtnv.getText());
        _sp.setSDT(txtsdt.getText());
        _sp.setDiaChi(txtdiachi.getText());
        _sp.setPhanQuyen(txtphanquyen.getText());

        Date dtn = txtdate.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        _sp.setNgaySinh(String.valueOf(dateFormat.format(dtn)));

        try {
            DAO.DAONhanVien.UpdateSP(_sp);
            LoadData2table();
            JOptionPane.showMessageDialog(this, "Sua thành công!");
        } catch (SQLException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btsuaMouseClicked

    private void btLammoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLammoiMouseClicked
        // TODO add your handling code here:
        Date a = new Date();
        txtManv.setText("");
        txtnv.setText("");
        txtdate.setDate(a);
        txtdiachi.setText("");
        txtsdt.setText("");
        txtphanquyen.setText("");

        try {
            LoadData2table();
        } catch (SQLException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btLammoiMouseClicked

    private void btnLammoiMouseClicked(java.awt.event.MouseEvent evt) {
        Date a = new Date();
        txtManv.setText("");
        txtnv.setText("");
        txtdate.setDate(a);
        txtdiachi.setText("");
        txtsdt.setText("");
        txtphanquyen.setText("");

        try {
            LoadData2table();
        } catch (SQLException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btLammoi;
    private com.k33ptoo.components.KButton btThem;
    private com.k33ptoo.components.KButton btXoa;
    private com.k33ptoo.components.KButton btsua;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDIACHI;
    private javax.swing.JLabel lbMANV;
    private javax.swing.JLabel lbNGAYSINH;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTEN;
    private javax.swing.JLabel lbphanquyen;
    private org.jdesktop.swingx.JXTable tbNhanvien;
    private javax.swing.JTextField txtManv;
    private org.jdesktop.swingx.JXDatePicker txtdate;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtnv;
    private javax.swing.JTextField txtphanquyen;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
