/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import Entity.Sua;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author G-up
 */
public class jpnSua extends javax.swing.JPanel {

    /**
     * Creates new form jpnSua
     */
    public jpnSua() throws SQLException, ClassNotFoundException {
        initComponents();
        loaddataTB();
        fillcombox();
    }
    
    private void fillcombox() {
        try {
            Connection cnn = TienIch.TienIch.getConnection();
            String sql = "select distinct Loai from SanPham";//lay nhung cai khac nhau
            PreparedStatement pStmt = cnn.prepareStatement(sql);
            ResultSet rs = pStmt.executeQuery();
            while (rs.next()){
                String Loaifill = rs.getString("Loai");
                cbLoai.addItem(Loaifill);
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmasp = new javax.swing.JTextField();
        txtTensp = new javax.swing.JTextField();
        cbLoai = new javax.swing.JComboBox<>();
        dtHangsd = new org.jdesktop.swingx.JXDatePicker();
        txtsoluong = new javax.swing.JTextField();
        txtdongia1 = new javax.swing.JTextField();
        lb_anh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSua = new org.jdesktop.swingx.JXTable();
        btnThem = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1170, 610));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Sữa");

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sữa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã sản phẩm: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Loại:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Hãng sử dụng:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số lượng:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Đơn giá:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        txtmasp.setBackground(new java.awt.Color(0, 255, 255));
        txtmasp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtmasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, -1));

        txtTensp.setBackground(new java.awt.Color(0, 255, 255));
        txtTensp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtTensp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 220, -1));

        cbLoai.setBackground(new java.awt.Color(0, 102, 102));
        cbLoai.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.add(cbLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 100, -1));

        dtHangsd.setBackground(new java.awt.Color(0, 153, 153));
        dtHangsd.setForeground(new java.awt.Color(0, 204, 204));
        dtHangsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtHangsdActionPerformed(evt);
            }
        });
        jPanel2.add(dtHangsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 180, -1));

        txtsoluong.setBackground(new java.awt.Color(0, 255, 255));
        txtsoluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtsoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 60, -1));

        txtdongia1.setBackground(new java.awt.Color(0, 255, 255));
        txtdongia1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtdongia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 100, -1));

        lb_anh.setText("ANH");
        jPanel2.add(lb_anh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, -50, 350, 400));

        tbSua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSuaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSua);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/update.png"))); // NOI18N
        btnLammoi.setText("Làm mới");
        btnLammoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLammoiMouseClicked(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/replacement.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/enter.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void dtHangsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtHangsdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtHangsdActionPerformed
    
    private void loaddataTB() throws SQLException, ClassNotFoundException {
        List<Sua> lstSanPham = DAO.DAOSua.getALL();
        // Thêm các tiêu đề cho cột bảng hiẻn thị
        DefaultTableModel tblModel = new DefaultTableModel();
        tblModel.addColumn("Mã sản phẩm");
        tblModel.addColumn("Tên sản phẩm");
        tblModel.addColumn("Loại");
        tblModel.addColumn("Hãng sử dụng");
        tblModel.addColumn("Đơn giá");
        tblModel.addColumn("Số lượng");
        tblModel.addColumn("Hình ảnh");
        // Add lần lượt các hàng vao bảng
        for (Sua _sanpham : lstSanPham)//trong lít sua
        {
            Vector<String> row = new Vector<String>();//row vector co 2 pahaafn tu ma , te, co3 thi ma , ten , loai, thanh 1 row
            row.addElement(String.valueOf(_sanpham.getMaSP()));//ep kieu ve string
            row.addElement(String.valueOf(_sanpham.getTenSP()));
            row.addElement(String.valueOf(_sanpham.getLoai()));
            row.addElement(String.valueOf(_sanpham.getHangSD()));
            row.addElement(String.valueOf(_sanpham.getDonGia()));
            row.addElement(String.valueOf(_sanpham.getSoLuong()));
            row.addElement(String.valueOf(_sanpham.getHinhAnh()));
            tblModel.addRow(row);//add cả row vao tblmodel từng vòng lặp 1 
        }
        tbSua.setModel(tblModel);//set ca tabel đã đặt tên cho table
    }
    
    private void loaddata_click() throws ParseException {//khi click thi load lai control
       //if (tbSua.getSelectedRow() != 1) {
            // xd hang da click
            //int i = tbSua.getSelectedRow();
            //lay danh sach tren co list<Sua>
            //List<Sua> lstSanPham = DAO.DAOSua.getALL();
            //xacdinh row day la cho nao da duoc click
            //Sua sua01 = lstSanPham.get(i);
            //set gia tri cho cac control
            //txtmasp.setText(sua01.getMaSP());
            //txtTensp.setText(String.valueOf(sua01.getTenSP()));
            //txtdongia.setText(String.valueOf(sua01.getDonGia()));
        //}
        
        //
        ImageIcon icon;
        //
        int i = tbSua.getSelectedRow();
        TableModel model = tbSua.getModel();
        txtmasp.setText(model.getValueAt(i, 0).toString());
        txtTensp.setText(model.getValueAt(i, 1).toString());
        txtdongia1.setText(model.getValueAt(i, 4).toString());
        txtsoluong.setText(model.getValueAt(i, 5).toString());
        //
        lb_anh.setText(model.getValueAt(i, 6).toString()); 
            icon = new ImageIcon("C:\\Users\\G-up\\OneDrive\\Documents\\NetBeansProjects\\QuanLyBanSua\\src\\anhSua\\"+model.getValueAt(i, 6).toString());            
            lb_anh.setIcon(icon);
            lb_anh.setText("");
        //
        String cbselect = model.getValueAt(i,2).toString();
            for (int j = 0; j < cbLoai.getItemCount(); j++) {
                if(cbLoai.getItemAt(j).equalsIgnoreCase(cbselect)){
                    cbLoai.setSelectedIndex(j);
                }
            
        }
            
        Date date = new SimpleDateFormat("yyy-MM-dd").parse((String)model.getValueAt(i, 3));
            dtHangsd.setDate(date);
            
            
//        try{
//            int srow = tbSua.getSelectedRow();
//            Date date = new SimpleDateFormat("yyy-MM-dd").parse((String)model.getValueAt(i, 3));
//            dtHangsd.setDate(date);
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }
    
    
    
    private void tbSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSuaMouseClicked
        try {
            loaddata_click();
        } catch (ParseException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbSuaMouseClicked

    private void btnLammoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLammoiMouseClicked
        txtTensp.setText("");
        txtmasp.setText("");
        txtdongia1.setText("");
        txtsoluong.setText("");
//        Date date = new SimpleDateFormat("yyy-MM-dd");
//        dtHangsd.setDate(date);
        cbLoai.setSelectedIndex(0);
        ImageIcon icon = new ImageIcon("");
        lb_anh.setIcon(icon);
        try {
            loaddataTB();
        } catch (SQLException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        }
        
          
    }//GEN-LAST:event_btnLammoiMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked

       //SimpleDateFormat datefr =new SimpleDateFormat("yyy-MM-dd");
        
        Sua _sp= new Sua();
       _sp.setMaSP(txtmasp.getText());
       _sp.setTenSP(txtTensp.getText());
       _sp.setSoLuong(Integer.valueOf(txtsoluong.getText()));
       _sp.setDonGia(Float.valueOf(txtdongia1.getText()));
       _sp.setLoai(cbLoai.getSelectedItem().toString());
       
        Date dtn = dtHangsd.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        _sp.setHangSD(dateFormat.format(dtn));
       
        try {
            DAO.DAOSua.InsertSP(_sp);
            JOptionPane.showMessageDialog(this, "Them thành công!");
            loaddataTB();
        } catch (SQLException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        try {
            DAO.DAOSua.DeleteSP(txtmasp.getText());
            loaddataTB();
            btnLammoiMouseClicked(evt);
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
        } catch (SQLException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
         Sua _sp= new Sua();
       _sp.setMaSP(txtmasp.getText());
       _sp.setTenSP(txtTensp.getText());
       _sp.setSoLuong(Integer.valueOf(txtsoluong.getText()));
       _sp.setDonGia(Float.valueOf(txtdongia1.getText()));
       _sp.setLoai(cbLoai.getSelectedItem().toString());
       
        Date dtn = dtHangsd.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        _sp.setHangSD(dateFormat.format(dtn));
        
        try {
            DAO.DAOSua.UpdateSP(_sp);
            loaddataTB();
            JOptionPane.showMessageDialog(this, "Sua thành công!");
        } catch (SQLException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpnSua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaMouseClicked
    // data acccess object
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình không", "HỎi xóa", JOptionPane.YES_NO_OPTION);
            if (hoi == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
    }//GEN-LAST:event_btnThoatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoai;
    private org.jdesktop.swingx.JXDatePicker dtHangsd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_anh;
    private org.jdesktop.swingx.JXTable tbSua;
    private javax.swing.JTextField txtTensp;
    private javax.swing.JTextField txtdongia1;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables

    
}
